
title: Mathews Malnar and Bailey, Inc.

# theme: minima
# minima:
#    skin: dark


# theme: jekyll-theme-cayman
# markdown: kramdown
# kramdown:
#   math_engine: mathjax
# markdown: GFM         # Garbles the table in index.md


# Build settings
remote_theme: jekyll/minima@3cdd14d
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

# Get the dark mode
minima:
    skin: dark

# Build settings
markdown: kramdown


# themes:
# https://foolishgeneralist.com/p/a-little-help-with-github-pages-and


# https://mantejjosan.github.io/math-made-easy/tut/

# https://github:com/PrasannaMaddila/prasannamaddila.github.io/blob/main/_config.yml
# Nice web page and has some useful items, including math
